[project]
authors = ["tobias fenner <toby@makerain.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "aircraft-nats"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
nats-py = "*"